#cloud-config
write_files:
  - path: /etc/systemd/system/alloy.service.d/override.conf
    permissions: '0600'
    content: |
      [Service]
      Environment="GCLOUD_SCRAPE_INTERVAL=${GCLOUD_SCRAPE_INTERVAL}"
      Environment="GCLOUD_RW_API_KEY=${GCLOUD_RW_API_KEY}"
      Environment="GCLOUD_HOSTED_LOGS_URL=${GCLOUD_HOSTED_LOGS_URL}"
      Environment="GCLOUD_HOSTED_LOGS_ID=${GCLOUD_HOSTED_LOGS_ID}"
      Environment="GCLOUD_HOSTED_METRICS_URL=${GCLOUD_HOSTED_METRICS_URL}"
      Environment="GCLOUD_HOSTED_METRICS_ID=${GCLOUD_HOSTED_METRICS_ID}"

# Caveat: 
# `runcmd` runs rather late in the cloud-init process, so early boot messages may not be captured
# An alternative would be to use `bootcmd`, but that runs before `write_files` is executed
# To verify the exact boot order, see /etc/cloud/cloud.cfg on the target system
runcmd:
  - systemctl enable alloy.service --now
