#cloud-config
write_files:
  - path: /etc/systemd/system/alloy.service.d/override.conf
    permissions: '0600'
    content: |
      [Service]
      Environment="GCLOUD_SCRAPE_INTERVAL=${GCLOUD_SCRAPE_INTERVAL}"
      Environment="GCLOUD_RW_API_KEY=${GCLOUD_RW_API_KEY}"
      Environment="GCLOUD_HOSTED_LOGS_URL=${GCLOUD_HOSTED_LOGS_URL}"
      Environment="GCLOUD_HOSTED_LOGS_ID=${GCLOUD_HOSTED_LOGS_ID}"
      Environment="GCLOUD_HOSTED_METRICS_URL=${GCLOUD_HOSTED_METRICS_URL}"
      Environment="GCLOUD_HOSTED_METRICS_ID=${GCLOUD_HOSTED_METRICS_ID}"

runcmd:
  - systemctl enable alloy.service --now
