name: test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  terraform_test:
    name: Terraform Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3
        # with:
        #   terraform_version: "1.11.1"
      - name: Terraform syntax & formatting checks
        run: make check-fmt
      - name: Run tests
        run: make test
